name: Issue Approval

on:
  issues:
    types: [opened, labeled]

jobs:
  approval:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install GitHub CLI and jq
      run: |
        sudo apt-get update
        sudo apt-get install -y gh jq

    - name: Configure GitHub CLI with GITHUB_TOKEN
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh auth status

    - name: Debug Environment Variables
      run: |
        echo "GitHub Event Path: $GITHUB_EVENT_PATH"
        cat $GITHUB_EVENT_PATH

    - name: Add pending-approval label on issue creation
      if: github.event.action == 'opened'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ISSUE_NUMBER=$(jq -r '.issue.number' "$GITHUB_EVENT_PATH")
        echo "Issue number: $ISSUE_NUMBER"
        gh issue edit $ISSUE_NUMBER --add-label "pending-approval"

    - name: Remove pending-approval label on approval
      if: github.event.action == 'labeled' && github.event.label.name == 'approved'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ISSUE_NUMBER=$(jq -r '.issue.number' "$GITHUB_EVENT_PATH")
        echo "Issue number: $ISSUE_NUMBER"
        gh issue edit $ISSUE_NUMBER --remove-label "pending-approval"
