name: Issue Approval

on:
  issues:
    types: [opened, labeled]

jobs:
  approval:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up GitHub CLI
      uses: actions/setup-node@v3
      with:
        node-version: '14'
      
    - name: Install GitHub CLI
      run: sudo apt-get install gh

    - name: Authenticate GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Add pending-approval label on issue creation
      if: github.event.action == 'opened'
      run: |
        ISSUE_NUMBER=$(jq -r '.issue.number' "$GITHUB_EVENT_PATH")
        gh issue edit $ISSUE_NUMBER --add-label "pending-approval"

    - name: Remove pending-approval label on approval
      if: github.event.action == 'labeled' && github.event.label.name == 'approved'
      run: |
        ISSUE_NUMBER=$(jq -r '.issue.number' "$GITHUB_EVENT_PATH")
        gh issue edit $ISSUE_NUMBER --remove-label "pending-approval"
